FROM public.ecr.aws/docker/library/node:gallium-alpine as baseline
ARG NPM_VER=next-8

ENV NODE_ENV=development

RUN npm install -g npm@${NPM_VER}
RUN apk update && apk upgrade && apk add bash openssh python3 alpine-sdk
WORKDIR /usr/src/app

FROM baseline as nextjs

COPY . .
CMD ["npx", "next", "dev"]

FROM baseline as npm-installer

CMD ["npm", "install"]
